### ISSUE TITLE
Documentation nits: https://staging.v.io/glossary.html

### ISSUE THREAD

**Issue by ivanpi-mtv** [vanadium/issues#384]
- [x] "See also" links have inconsistent capitalization ("blessing patterns" -> "Blessing Pattern", "Contribution instructions" etc) and inconsistently end with a period
- [x] Access List: "describles" -> "describes"
- [x] Blessing: "name" should link to glossary entry?
- [x] Blessing: emphasize "extension" since it is linked to
- [x] Blessing Name: "principal" (first time it appears, in first line, instead of near the end), "server" (service? #314 ), "caveats" should link to glossary entry
- [ ] Blessing Pattern: quotes around pattern redundant?
- [x] Blessing Pattern: "matched exactly by the" -> "matched only by the exact"
- [x] Caveat: "conditions placed in" -> "conditions placed on"
- [ ] Caveat: "peers" should link to glossary entry #191
- [x] Client: "caller-side" -> "caller side"
- [x] Credentials: "principal and" - Oxford comma #309 
- [x] Discharge: "third-party caveat" should link to glossary entry; "caveat" first time it appears
- [x] Endpoint: start with "An endpoint"
- [ ] Identity Provider: "certificate forging" links to a paper on a personal website instead of an article publisher/aggregator entry or a more general Wikipedia entry
- [x] Mount Table: lowercase in text ("A mount table)?
- [ ] Mount Table: server or service?
- [x] Namespace: lowercase in text?
- [x] Namespace: "object names" should link to glossary entry (even though it is just below)
- [x] Object name: start with "An object name"
- [ ] Object Name: "Also called: name" -> "name" should also work as a link
- [ ] Principal: "public and private key pair" -> "entity identified by a public and private key pair"?
- [x] RPC: "call enables communications" -> "calls enable communication"
- [ ] RPC: "processes" -> "peers" (+link)?
- [x] Server: "receiver-side" -> "receiver side"
- [x] Server: second sentence "The term <i>server</i>"
- [x] Suffix: start with "A suffix"
- [ ] Third-party Caveat: "burden", "pushed" sound odd
- [x] Third-party Caveat: "recepient" -> "recipient"
- [x] Third-party Caveat: redundant comma after "include"
- [ ] Third-party Caveat: proximity is not adequately explained
- [ ] Third-party Caveat: "wielder" - we don't use that word elsewhere?
- [x] v23: "and is" -> "which is"
- [ ] VOM: mention where it is used (RPC)?
- [x] VOM: "Java and" - Oxford comma #309 
- [x] WSPR: "Websocket", "WebSocket" inconsistency
- [x] WSPR: "node" -> "Node.js"
- [x] WSPR: "the WebSocket" -> "WebSocket"; "a conventional RPC" -> "conventional RPCs"; "the response" -> "responses"
- [x] some command names (e.g. vrpc) not styled as code
- [x] add links to Vanadium Security Concepts where appropriate?
