### ISSUE TITLE
JS Tutorial Feedback

### ISSUE THREAD

**Issue by afandria** [vanadium/issues#424]
Thanks to @herbertc11 for his feedback.

@afandria @bprosnitz @lnizix 
# General
- [x] Copy to clipboard feedback isn't enough. It only seems to be for mousedown. It needs to be a few seconds longer, or for focus, or until a different one is clicked so that it persists longer. (Tracked in #433)
- [x] Seekblessings tab doesn't say it can be closed or have a mechanism for autoclosing #423
- [ ] The 'Next Tutorial' button is hard to see.
- [x] Prerequisites isn't clear. The box itself is hard to read. There's a lot of friction here. [Perhaps say needs to reiterate that sourcing these completer scripts will set your tutorial state up as if you had done the prerequisite tutorials.] Tracked in #308 and #437
- [ ] Should the Copy button be moved to the bottom of the code block? Otherwise, one will need to scroll back up after reading the box through. [Moving it to the bottom will also encourage reading the box before running the command.]
- [x] basics and client/server => Client/Server Basics
# Overview
- [x] Vanadium is used to build secure distributed web applications isn't totally right [How about 'can be used' instead?]
# Hello Peer
## Setup
- [ ] Possibly add hint to check if you have nodejs. [try typing `node` or `which node` instead of `nodejs`]
- [x] Make the text for `https:golang.org/dl` into a normal link
- [ ] Did the copy button fail for the pre-release section?
## Creating a Vanadium Application
- [x] Make it more obvious that they do not need to copy the code. **The full file will be shown afterwards.**
- [x] `context` and `serverCall`. They aren't in backticks yet.
- [ ] peer.js is huge. Can we do anything about this?
## Viewing in a browser
- [x] Perhaps we should send the node-static output to /dev/null. Everyone goes to http://127.0.0.1:8999 even though we didn't create an index.html file.
- [x] Move the description of seeing 2 peers upwards before visiting the page.
- [ ] Pressing Enter in the textbox doesn't do anything; we never hooked up that KeyEvent.
# Fortune in JS
- [ ] Lots of confusion about prereqs. It needs to be clear that they need to Install Vanadium and Run the Completer Script 
## Defining the Fortune Service
- [x] VDL Link to the glossary didn't go to the right anchortext (cannot reproduce on OSX or Linux)
- [ ] It may be worth repeating inline help sections in case our prereq box is insufficient. (Upon running the vdl tool, it would be the perfect time to say that if it errors, you need to go back and fix things.)
## Fortune Server
- [ ] Syntax highlighting still wrong in config
- [x] Serving at a name: "Vanadium name" needs a glossary link, and the naming tutorial links need to be moved up.
## Fortune Client
- [x] Summaries of the following codeblocks are good. Consider adding more.
## Running Fortune
- [x] Add a clearer link to the Cleanup section for those who want to skip the Interoperating with Go section (or need to stop doing the tutorial).
- [x] Node-static is different here, compared to Hello Peer. Make it more consistent to reduce cognitive load.
## Interoperating with Go
- [x] Go client + JS Server command didn't work because of cut. We need an alternative (Related #422) Tracked in #428
- [ ] Go server was running in the background, but didn't look like it.
- [ ] Mac server port warning (even though it's not needed. We should mention that it will happen? Look at Client/Server Basics)
- [x] JS client to Go server was not working during this test. We must re-verify that it does with the latest extension.
# Conclusions
- [x] Copying stuff is good, at the cost of potentially not learning.
- [ ] Code changes are more engaging for certain developers. We could include a few example ideas at the end of each JS tutorial.
- [ ] Make the effects of running source clearer, and inline. (Just downloads code and adds env_vars)
- [ ] Link to the FAQ more, since it has a lot of clarifying answers.
